name: Test Workflow with PostgreSQL
on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  backup_db:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password  # Set the PostgreSQL password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Backup PostgreSQL Database
        env:
          PGPASSWORD: ${{ secrets.POSTGRES_TEST_PASSWORD }}
        run: |
          pg_dump -h localhost -U test_user -d test_db -F c -b -v -f "backup.pgsql"
      
      - name: Upload Backup as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: postgres_backup
          path: "backup.pgsql"


