name: Test Workflow with PostgreSQL
on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  backup_db:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432  # Expose the correct port
        options: >-  # Optional, for better resilience
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 5  # Adjust as needed
          done
        env:
          PGPASSWORD: postgres  # PostgreSQL password

      - name: Connect to PostgreSQL and Create Database
        env:
          PGPASSWORD: postgres  # Use GitHub Secrets for secure password handling
        run: |
          # Connect to PostgreSQL server and create a new database
          psql -h localhost -U postgres -c "CREATE DATABASE new_db;"
          
      - name: Backup PostgreSQL Database
        env:
          PGPASSWORD: postgres
        run: |
          pg_dump -h localhost -U postgres -d new_db -F c -b -v -f "backup.pgsql"




