name: Test Workflow with PostgreSQL
on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password  # Correctly set the password here
          POSTGRES_DB: test_db
        ports:
          - 5432:5432  # PostgreSQL default port

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Test with PostgreSQL
        env:
          PGPASSWORD: ${{ secrets.POSTGRES_TEST_PASSWORD }}  # Use GitHub Actions secrets to securely provide the password
        run: |
          # Test database connection with the correct password
          psql -h localhost -U test_user -d test_db -c "SELECT 'Connection successful!';"

